### ISSUE TITLE
Projekta se ne da odpreti v Binderju

### ISSUE THREAD

**Issue by jankoprogramko** [jankoprogramko/APPR-2020-21#1]
Pozdravljeni,

moj projekt je sicer končan, vendar mi, ko ga skušam odpreti v Binderju javi napako. V `README.md` sem spremenil podatke za povezavo.

Za pomoč se zahvaljujem.

Lep pozdrav,
Jan Črne

**Comment by jaanos** [comment]
Glede delovanja na Binderju sem ti odprl pull request #2. Drugače pa projekt deluje, tako da bom dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Imam samo eno manjšo estetsko pripombo: med vrstici
https://github.com/jankoprogramko/APPR-2020-21/blob/7333bcbcad9b2824a1a16d53413d59a801d53a18/projekt.Rmd#L238-L239
vstavi še prazno vrstico, da se namesto zvezdic izpiše vodoravna črta (lahko pa tudi zvezdice pobrišeš, če je nočeš).
